### PR TITLE
Update edge-proxy

### PR DESCRIPTION
**Pull request by moonchen**
Update edge-proxy to include the new HTTPS proxy based on HTTP CONNECT.

### CODE REVIEW

**Review by costanic — CHANGES_REQUESTED** [review]
We already have https://github.com/PelionIoT/snap-pelion-edge/pull/335 for upgrading edge-proxy.  Why not work from there?

**Comment by moonchen** [comment]
> We already have #335 for upgrading edge-proxy. Why not work from there?

I made this a different PR because this incorporates a different update.

**Comment by moonchen** [comment]
TODO: update the SHA after https://github.com/PelionIoT/edge-proxy/pull/11 has been merged.

**Review by costanic — APPROVED** [review]

**Review by johnmichaelwelsh — APPROVED** [review]

**Review by mray190 — APPROVED** [review]
If it passes CI, good with me

**Pull request merged**
