### PR TITLE
Upgraded Edge core and Maestro to add GRM feature

### PR DESCRIPTION
**Pull request by ygoyal18**
This allows Maestro to add new LwM2M resources to gateway device. These
resources represents the gateway capabilities, meaning the rich node services which are
running on the gateway, for example - KaaS, Logging and Terminal. Maestro also pushes the
configuration data which is associated to the services.

1. Updated Edge Core to 0.15.0, also added the CMake flags related to new FOTA library, to
indicate to readers that new FOTA framework library is not compilied in Edge Core.
1. Updated maestro to v2.9.0, which consumes GRM APIs and also removes the parsing of
self-signed certificate from identity.json
1. Updated maestro configuration to register new LwM2M resources advertising static gateway
capabilities.

Remote configuration management via LwM2M -
With this feature, user can update the configuration of the service like
Maestro logs, KaaS or Terminal via LwM2M. Maestro on receiving this write request will update
the configuration file on the gateway. Missing bit - How to restart the service after config file is updated?

May be we can reuse how its done on Yocto - a systemd watcher file which detects the config file
change and restarts the respective service.

### CODE REVIEW

**Comment by ygoyal18** [comment]
The automated job is failing to apply patch 0001-fix-calculation-of-remaining-buffer-size-when-callin.patch. I checked and looks like the patch has been upstreamed - https://github.com/PelionIoT/mbed-cloud-client/blob/master/update-client-hub/modules/pal-linux/source/arm_uc_pal_linux_implementation_internal.c#L178

I will remove the patch to see if the job goes further but please verify.

**Comment by costanic** [comment]
> The automated job is failing to apply patch 0001-fix-calculation-of-remaining-buffer-size-when-callin.patch. I checked and looks like the patch has been upstreamed - https://github.com/PelionIoT/mbed-cloud-client/blob/master/update-client-hub/modules/pal-linux/source/arm_uc_pal_linux_implementation_internal.c#L178
> 
> I will remove the patch to see if the job goes further but please verify.

@ygoyal18 I'm sure the remaining patches will need to be changed substantially due to new/modified APIs from 0.13.0 to 0.15.0 around adding resources to edge-core at startup time.  This may be a significant additional effort to upgrade to 0.15.0.

Also, should we expect more PRs to upgrade the remaining components so that they are in sync with Pelion Edge Version 2.2?  I think it makes sense to move completely to 2.2 since those components/versions are known to work together.

**Comment by costanic** [comment]
@ygoyal18 https://github.com/PelionIoT/snap-pelion-edge/pull/363 incorporates the changes made here, plus all patches are ported and fixed, plus it's based on the current dev branch.  Please check it out, and if you find it ok, we can close this PR in favor of the other one.

**Comment by ygoyal18** [comment]
> @ygoyal18 #363 incorporates the changes made here, plus all patches are ported and fixed, plus it's based on the current dev branch. Please check it out, and if you find it ok, we can close this PR in favor of the other one.

@costanic The PR looks good to me.. The only change I noticed was maestro SHA but looks like dev is already on latest so all good.

**Comment by costanic** [comment]
> > @ygoyal18 #363 incorporates the changes made here, plus all patches are ported and fixed, plus it's based on the current dev branch. Please check it out, and if you find it ok, we can close this PR in favor of the other one.
> 
>  maestro SHA but looks like dev is already on latest so all good.

Yes, that's right.  The only extra change I needed was the maestro config.

**Comment by costanic** [comment]
Closing this because the same content was merged in https://github.com/PelionIoT/snap-pelion-edge/pull/363

**Pull request closed without merging**
