### PR TITLE
Upgraded pe-utils to 2.0.6

### PR DESCRIPTION
**Pull request by ygoyal18**
This version of pe-utils mainly add a generic derivation in identity-tool to generate edge gw urls from all possible values of LwM2M service address. This should allow snap-pelion-edge gateways to connect with any Pelion cloud and on-prem instance.

### CODE REVIEW

**Review by OPpuolitaival — APPROVED** [review]

**Comment by costanic** [comment]
@ygoyal18 The PR seems fine but CI is failing.  I haven't looked at the failure yet, have you?

**Comment by costanic** [comment]
@ygoyal18 While the CI is investigated, one criticism I have would be to change the `source-commit: SHA` to a `source-tag: TAG` since we have a tag available.  See [edge-core](https://github.com/PelionIoT/snap-pelion-edge/blob/14ed04d6e5aebe497c87635dfab6691fff9d5a9e/snap/snapcraft.yaml#L220) for an example of how to specify a tag instead of a SHA.

**Comment by ygoyal18** [comment]
@OPpuolitaival These PR checks are correctly indicating that changes to identity-tool are not working. I will raise another PR which will bring the fix to the identity-tool and close this one.

@costanic Thanks for the information. Its definitely easier to follow the tags. I will use that in upcoming PR.

**Comment by ygoyal18** [comment]
Closing in favor of https://github.com/PelionIoT/snap-pelion-edge/pull/382

**Pull request closed without merging**
