### PR TITLE
Add local host and forward address for container domain

### PR DESCRIPTION
**Pull request by ashishwigwag**
1. Modify edge-proxy launch script to add new forwarding address for containers domain
2. Add `containers.local` to the list of known hosts

### CODE REVIEW

**Comment by ashishwigwag** [comment]
Need to update `pe-utils` after version 2.0.5 is out.

**Comment by costanic** [comment]
> Need to update `pe-utils` after version 2.0.5 is out.
@ashishwigwag Is this PR dependent on the upgrade, or is this change fine on its own?

**Comment by ygoyal18** [comment]
@ashishwigwag pe-utils v2.0.5 is already available. Please pull that in as well. 
@costanic Yes, this PR is dependent on pe-utils v2.0.5.

**Comment by costanic** [comment]
> @ashishwigwag pe-utils v2.0.5 is already available. Please pull that in as well.
> @costanic Yes, this PR is dependent on pe-utils v2.0.5.

ok, let's add that to this PR.

**Comment by ashishwigwag** [comment]
> > @ashishwigwag pe-utils v2.0.5 is already available. Please pull that in as well.
> > @costanic Yes, this PR is dependent on pe-utils v2.0.5.
> 
> ok, let's add that to this PR.

Updated pe-utils source commit to latest.

**Review by CristianPrundeanuARM — APPROVED** [review]
LGTM

**Comment by costanic** [comment]
Rebased on current dev branch.

@ashishwigwag please make sure this PR is still needed and still looks good after the rebase.

**Review by costanic — APPROVED** [review]

**Comment by ashishwigwag** [comment]
> Rebased on current dev branch.
> 
> @ashishwigwag please make sure this PR is still needed and still looks good after the rebase.

Yes, still needed.

@ygoyal18 Can we merge this?

**Comment by costanic** [comment]
Since [pe-utils was upgraded to 2.0.7](https://github.com/PelionIoT/snap-pelion-edge/pull/382), this seems ready to go.

**Pull request merged**
