### PR TITLE
Maestro cleanup

### PR DESCRIPTION
**Pull request by mray190**
Not urgent
Removes un-used maestro features like mdns, templating, devicedb, and logging

### CODE REVIEW

**Comment by mray190** [comment]
See a similar PR for distro-pelion-edge:
https://github.com/PelionIoT/distro-pelion-edge/pull/179

**Review by costanic — CHANGES_REQUESTED** [review]
Can you modify each commit message to mention specifically that the change is to the maestro config.  For example, "Removed devicedb daemon and configuration" makes me think that devicedb daemon is removed from the snapcraft.yaml.  Same with "Remove unused feature mdns".  In isolation if viewed in git-history it won't be obvious that it's a maestro config change.

**Comment by mray190** [comment]
> Can you modify each commit message to mention specifically that the change is to the maestro config. For example, "Removed devicedb daemon and configuration" makes me think that devicedb daemon is removed from the snapcraft.yaml. Same with "Remove unused feature mdns". In isolation if viewed in git-history it won't be obvious that it's a maestro config change.

Yeah I can do that. To be clear though, this does remove the devicedb daemon, AND modifies the config.
So I can modify each commit to specify configuration vs daemon. But still doesn't change the fact that I remove the daemon as well.

Would it be useful for me to split the commits where i remove a daemon and adjust a config?

**Comment by costanic** [comment]
> > Can you modify each commit message to mention specifically that the change is to the maestro config. For example, "Removed devicedb daemon and configuration" makes me think that devicedb daemon is removed from the snapcraft.yaml. Same with "Remove unused feature mdns". In isolation if viewed in git-history it won't be obvious that it's a maestro config change.
> 
> Yeah I can do that. To be clear though, this does remove the devicedb daemon, AND modifies the config.
> So I can modify each commit to specify configuration vs daemon. But still doesn't change the fact that I remove the daemon as well.
> 
> Would it be useful for me to split the commits where i remove a daemon and adjust a config?

hmm.  I missed the removal from the snapcraft.yaml file.  I swear I checked it twice before I commented.  weird.

**Review by costanic — APPROVED** [review]

**Pull request merged**
