### PR TITLE
Modify edge-core patch to include human readable platform version LWM2M

### PR DESCRIPTION
**Pull request by mray190**
Read file /etc/readable_version into a LWM2M object /10252/0/11

Keep the original functionality of reading /etc/platform_version
into LWM2M object /10252/0/10

### CODE REVIEW

**Comment by mray190** [comment]
Confirmed in the snap. Had to fix some bugs hence the force pushes

**Review by johnmichaelwelsh — APPROVED** [review]
All looks good. Does it run?

**Review by costanic — COMMENTED** [review]
I think the value of defaultVersion is -1, which means this won't pass our Test criteria.

**Comment by mray190** [comment]
> I think the value of defaultVersion is -1, which means this won't pass our Test criteria.

The default values for all LWM2M objects is -1. I thought it would be good to keep the defaults the same, hence keeping it at -1. Should we change the default value to "", or should we talk to Ryan and allow -1? I'm okay with either

**Review by costanic — APPROVED** [review]

**Comment by costanic** [comment]
CI failed with the following error.  Doesn't look like it's related to this PR.

> 
> Still waiting to schedule task
> ‘EC2 (ec2-eu-west-1) - pelion-edge-test-slave (i-0cf384c021495fa49)’ is offline
> ‘EC2 (ec2-eu-west-1) - pelion-edge-test-slave (i-0d3bff7f00ed57d12)’ is offline
> ‘Jenkins’ doesn’t have label ‘pelion-edge-test’
> ‘oulab2.mbedcloudtesting.com_01’ doesn’t have label ‘pelion-edge-test’
> ‘oulab2.mbedcloudtesting.com_02’ doesn’t have label ‘pelion-edge-test’
> ‘pelion-edge-test-slave-static’ doesn’t have label ‘pelion-edge-test’
> Running on EC2 (ec2-eu-west-1) - pelion-edge-test-slave (i-020e93197051db593) in /home/ubuntu/ws/repo-snap-pelion-edge_PR-313
> [Pipeline] {
> [Pipeline] stage
> [Pipeline] { (setup tests)
> [Pipeline] unstash
> [Pipeline] sh
> + mv pelion-edge_1.19.0_amd64.snap pelion-edge_amd64.snap pelion-edge_amd64.snap
> mv: target 'pelion-edge_amd64.snap' is not a directory
> [Pipeline] }
> [Pipeline] // stage
> [Pipeline] }
> [Pipeline] // node
> [Pipeline] End of Pipeline
> [Checks API] No suitable checks publisher found.
>

**Pull request merged**
