### PR TITLE
Remove active empty ENV parameters and add details to comment

### PR DESCRIPTION
**Pull request by CristianPrundeanuARM**
Signed-off-by: Cristian Prundeanu <cristian.prundeanu@arm.com>

### CODE REVIEW

**Review by costanic — CHANGES_REQUESTED** [review]
I'm confused here.  [According to the docs](https://docs.docker.com/engine/reference/builder/#env), `--env` overrides `ENV`, but this comment makes it seem like it's the other way around.

**Comment by CristianPrundeanuARM** [comment]
> I'm confused here. [According to the docs](https://docs.docker.com/engine/reference/builder/#env), `--env` overrides `ENV`, but this comment makes it seem like it's the other way around.

It is the other way around from empirical observation. Having `ENV` entries makes the corresponding `--env` parameters have no effect.

**Comment by costanic** [comment]
> > I'm confused here. [According to the docs](https://docs.docker.com/engine/reference/builder/#env), `--env` overrides `ENV`, but this comment makes it seem like it's the other way around.
> 
> It _**is**_ the other way around from empirical observation. Having `ENV` entries makes the corresponding `--env` parameters have no effect.

ok.  I feel we need to get to the bottom of this before merging this change, given this is explicitly contradicted by the docker docs.    Or maybe create an issue in the docker repo and link it here?  Maybe there's already an open issue.

**Comment by ryannowarm** [comment]
> > It _**is**_ the other way around from empirical observation. Having `ENV` entries makes the corresponding `--env` parameters have no effect.

Hrmmm, I haven't seen this.

> ok. I feel we need to get to the bottom of this before merging this change, given this is explicitly contradicted by the docker docs.

Agreed

**Comment by CristianPrundeanuARM** [comment]
Don't know what's happening. Now when I check environment inside the container, it is correctly taken from docker's `--env` parameters, overriding `ENV` in the `Dockerfile`.

**Comment by CristianPrundeanuARM** [comment]
This is still an issue in some configurations, commenting the ENV lines correctly passes the command line variables. Reopening PR.

**Review by costanic — APPROVED** [review]

**Pull request merged**
