### PR TITLE
v2.3.0 dev->master

### PR DESCRIPTION
**Pull request by mray190**
Proposed Release Notes:
* Upgrade: edge-core 0.16.1
* Upgrade: pe-utils 2.0.7
* Upgrade: docker v19.03.13
* Bug fix: Kubelet secrets mounting permissions
* Bug fix: Add local host and forward address for containers in edge-proxy startup
* Feature: Add ARG to Dockerfile

### CODE REVIEW

**Comment by mray190** [comment]
Do not merge until v2.3.0-1 tag has made it onto `dev`

PR waiting CI and approval: https://github.com/PelionIoT/snap-pelion-edge/pull/384

**Comment by mray190** [comment]
Needs `--ff-only` tag from command line to merge. do not merge via UI

**Review by costanic — APPROVED** [review]
Seems fine except for the release note comment about adding an ARG to the Dockerfile.  We might want to add some more explanation about that.

**Comment by mray190** [comment]
> Seems fine except for the release note comment about adding an ARG to the Dockerfile. We might want to add some more explanation about that.

I will add more details in the release notes

**Comment by mray190** [comment]
Original PR for the v2.3.0-1 release passed CI. See:
https://github.com/PelionIoT/snap-pelion-edge/pull/384/commits/7933f071763b6949ace224e70179284fd21d424b

This PR is reporting CI failure on the exact same commit, 30 minutes later.

Will report CI job failure as a bug, but will merge as is for now

**Pull request merged**
